language: php

php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run --config=phpspec.yml --no-interaction
